### PR TITLE
Add conda setup instructions

### PR DESCRIPTION
**Pull request by BenGalewsky**
# Problem
MLFlow requires Conda to manage environments.

# Approach
Added simple instructions for installing Conda in your account on DGX

### CODE REVIEW

**Comment by msneubauer** [comment]
Looks good. Thanks. The REAME has been more of a dumping ground for me right now, so this is a welcome contribution.

**Comment by msneubauer** [comment]
My mistake above. I thought this was the vbs-analysis README but I see its Matthew's DGX instructions which are good!

**Review by matthewfeickert — COMMENTED** [review]
@BenGalewsky Does this properly isolate Miniconda? I think this as is if you login to DGX and do

```console
$ which python
```

you'll get Conda's. This isn't terrible to have it as the default, but if you login do you get the following (if you had an exisitng `pyenv` environment named `base`)?

```console
$ pyenv activate base
$ which python
~/.pyenv/shims/python
$ pyenv which python
/raid/projects/<whatever your user name is here>/.pyenv/versions/base/bin/python
```

or does Conda leek in?

**Comment by matthewfeickert** [comment]
What would be better yet still is to have `pyenv` install and manage Conda and then just direct `mlflow` to use a different default value of `MLFLOW_CONDA_HOME`. c.f. https://www.mlflow.org/docs/latest/projects.html#project-environments

edit: The setting of `MLFLOW_CONDA_HOME` shouldn't be needed as `pyenv` will still add the `condabin` to `PATH` during installation.

**Comment by matthewfeickert** [comment]
Okay yeah. If I truncate at my `matthewfeickert/pyenv-virtualenv-conda` Dockerfile [at this line](https://github.com/matthewfeickert/pyenv-virtualenv-conda-example/blob/eedac7b90ed372fe940f3c41456c0d5c415b7642/Dockerfile#L77) so that Miniconda doesn't get installed and then build it then

```
$ docker run --rm -ti matthewfeickert/pyenv-virtualenv
$ wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh
$ bash Miniconda3-py38_4.10.3-Linux-x86_64.sh  # Answering yes to all defaults
$ . ~/.bashrc  # to mimic restarting shell
$ which python  
/home/docker/miniconda3/bin/python
$ pyenv virtualenv 3.8.11 test
$ pyenv activate test
$ which python  # problem here as python is getting Conda's and not the pyenv one we want
/home/docker/miniconda3/bin/python
```

So the solution is to [add](https://github.com/matthewfeickert/pyenv-virtualenv-conda-example/blob/eedac7b90ed372fe940f3c41456c0d5c415b7642/Dockerfile#L82)

```console
conda config --set auto_activate_base false
```

which results in 

```console
$ cat ~/.condarc 
auto_activate_base: false
```

and probably also have `pyenv` control things to make it easier overall.

**Pull request merged**
